export const CS_FOLD = 'CS_FOLD';
export const CS_CHECK = 'CS_CHECK';
export const CS_CALL = 'CS_CALL';
export const CS_RAISE = 'CS_RAISE';
export const WINNER = 'WINNER';
export const CS_FETCH_LOBBY_INFO = 'CS_FETCH_LOBBY_INFO';
export const SC_RECEIVE_LOBBY_INFO = 'SC_RECEIVE_LOBBY_INFO';
export const SC_PLAYERS_UPDATED = 'SC_PLAYERS_UPDATED';
export const CS_JOIN_TABLE = 'CS_JOIN_TABLE';
export const SC_TABLE_JOINED = 'SC_TABLE_JOINED';
export const CS_LEAVE_TABLE = 'CS_LEAVE_TABLE';
export const SC_TABLE_LEFT = 'SC_TABLE_LEFT';
export const SC_TABLES_UPDATED = 'SC_TABLES_UPDATED';
export const SC_TABLE_UPDATED = 'SC_TABLE_UPDATED';
export const TABLE_MESSAGE = 'TABLE_MESSAGE';         // no emit event
export const CS_REBUY = 'CS_REBUY';
export const CS_SIT_DOWN = 'CS_SIT_DOWN';
export const CS_STAND_UP = 'CS_STAND_UP';
export const SITTING_OUT = 'SITTING_OUT';         // no emit event
export const SITTING_IN = 'SITTING_IN';         // no emit event
export const CS_DISCONNECT = 'CS_DISCONNECT';

// Blockchain integration events
export const CS_JOIN_TABLE_BLOCKCHAIN = 'CS_JOIN_TABLE_BLOCKCHAIN';
export const CS_LEAVE_TABLE_BLOCKCHAIN = 'CS_LEAVE_TABLE_BLOCKCHAIN';
export const SC_BLOCKCHAIN_STATUS = 'SC_BLOCKCHAIN_STATUS';
export const SC_BLOCKCHAIN_TX_STATUS = 'SC_BLOCKCHAIN_TX_STATUS';
export const SC_BLOCKCHAIN_ERROR = 'SC_BLOCKCHAIN_ERROR';
export const SC_BLOCKCHAIN_SETTLEMENT = 'SC_BLOCKCHAIN_SETTLEMENT';
export const SC_BALANCE_SYNCED = 'SC_BALANCE_SYNCED';

// Player-signed contract calls (frontend calls contract directly)
export const CS_CONTRACT_JOIN_SUCCESS = 'CS_CONTRACT_JOIN_SUCCESS';
export const CS_CONTRACT_JOIN_FAILED = 'CS_CONTRACT_JOIN_FAILED';
export const CS_CONTRACT_LEAVE_SUCCESS = 'CS_CONTRACT_LEAVE_SUCCESS';
export const CS_CONTRACT_LEAVE_FAILED = 'CS_CONTRACT_LEAVE_FAILED';

// Delegate (Server Proxy) events
export const CS_SET_DELEGATE = 'CS_SET_DELEGATE';
export const SC_DELEGATE_SET = 'SC_DELEGATE_SET';
export const SC_DELEGATE_ERROR = 'SC_DELEGATE_ERROR';
export const CS_CHECK_DELEGATE = 'CS_CHECK_DELEGATE';
export const SC_DELEGATE_STATUS = 'SC_DELEGATE_STATUS';
export const CS_REVOKE_DELEGATE = 'CS_REVOKE_DELEGATE';
export const SC_DELEGATE_REVOKED = 'SC_DELEGATE_REVOKED';

// Tournament System events
export const CS_TOURNAMENT_LIST = 'CS_TOURNAMENT_LIST';
export const SC_TOURNAMENT_LIST = 'SC_TOURNAMENT_LIST';
export const CS_TOURNAMENT_JOIN = 'CS_TOURNAMENT_JOIN';
export const SC_TOURNAMENT_JOINED = 'SC_TOURNAMENT_JOINED';
export const SC_TOURNAMENT_JOIN_ERROR = 'SC_TOURNAMENT_JOIN_ERROR';
export const CS_TOURNAMENT_CANCEL = 'CS_TOURNAMENT_CANCEL';
export const SC_TOURNAMENT_CANCELLED = 'SC_TOURNAMENT_CANCELLED';
export const SC_TOURNAMENT_STARTED = 'SC_TOURNAMENT_STARTED';
export const SC_TOURNAMENT_ENDED = 'SC_TOURNAMENT_ENDED';
export const SC_TOURNAMENT_UPDATE = 'SC_TOURNAMENT_UPDATE';
export const SC_TOURNAMENT_ELIMINATION = 'SC_TOURNAMENT_ELIMINATION';
export const SC_TOURNAMENT_PRIZE = 'SC_TOURNAMENT_PRIZE';
// Tournament game actions
export const CS_TOURNAMENT_FOLD = 'CS_TOURNAMENT_FOLD';
export const CS_TOURNAMENT_CHECK = 'CS_TOURNAMENT_CHECK';
export const CS_TOURNAMENT_CALL = 'CS_TOURNAMENT_CALL';
export const CS_TOURNAMENT_RAISE = 'CS_TOURNAMENT_RAISE';
export const CS_TOURNAMENT_RECONNECT = 'CS_TOURNAMENT_RECONNECT';
export const SC_TOURNAMENT_GAME_STATE = 'SC_TOURNAMENT_GAME_STATE';
export const SC_TOURNAMENT_ACTION_ERROR = 'SC_TOURNAMENT_ACTION_ERROR';

// NFT Achievement events
export const CS_NFT_CHECK_ACHIEVEMENT = 'CS_NFT_CHECK_ACHIEVEMENT';
export const SC_NFT_ACHIEVEMENT_EARNED = 'SC_NFT_ACHIEVEMENT_EARNED';
export const SC_NFT_ACHIEVEMENT_NONE = 'SC_NFT_ACHIEVEMENT_NONE';
export const CS_NFT_PREPARE_MINT = 'CS_NFT_PREPARE_MINT';
export const SC_NFT_MINT_READY = 'SC_NFT_MINT_READY';
export const SC_NFT_MINT_ERROR = 'SC_NFT_MINT_ERROR';
export const CS_NFT_COLLECTION = 'CS_NFT_COLLECTION';
export const SC_NFT_COLLECTION = 'SC_NFT_COLLECTION';

// CHIP Token events
export const CS_CHIP_BALANCE = 'CS_CHIP_BALANCE';
export const SC_CHIP_BALANCE = 'SC_CHIP_BALANCE';
export const CS_CHIP_REWARD = 'CS_CHIP_REWARD';
export const SC_CHIP_REWARDED = 'SC_CHIP_REWARDED';
export const SC_CHIP_VIP_DISCOUNT = 'SC_CHIP_VIP_DISCOUNT';

// Staking events
export const CS_STAKE_INFO = 'CS_STAKE_INFO';
export const SC_STAKE_INFO = 'SC_STAKE_INFO';
export const CS_STAKE_CREATE = 'CS_STAKE_CREATE';
export const SC_STAKE_CREATED = 'SC_STAKE_CREATED';
export const SC_STAKE_ERROR = 'SC_STAKE_ERROR';
export const CS_STAKE_UNSTAKE = 'CS_STAKE_UNSTAKE';
export const SC_STAKE_UNSTAKED = 'SC_STAKE_UNSTAKED';
export const CS_STAKE_CLAIM_REWARD = 'CS_STAKE_CLAIM_REWARD';
export const SC_STAKE_REWARD_CLAIMED = 'SC_STAKE_REWARD_CLAIMED';

// DAO Governance events
export const CS_DAO_PROPOSALS = 'CS_DAO_PROPOSALS';
export const SC_DAO_PROPOSALS = 'SC_DAO_PROPOSALS';
export const CS_DAO_CREATE_PROPOSAL = 'CS_DAO_CREATE_PROPOSAL';
export const SC_DAO_PROPOSAL_CREATED = 'SC_DAO_PROPOSAL_CREATED';
export const CS_DAO_VOTE = 'CS_DAO_VOTE';
export const SC_DAO_VOTED = 'SC_DAO_VOTED';
export const SC_DAO_PROPOSAL_EXECUTED = 'SC_DAO_PROPOSAL_EXECUTED';
export const SC_DAO_PROPOSAL_STATE_CHANGED = 'SC_DAO_PROPOSAL_STATE_CHANGED';

// AI Autopilot events
export const CS_AI_ENABLE = 'CS_AI_ENABLE';
export const SC_AI_ENABLED = 'SC_AI_ENABLED';
export const CS_AI_DISABLE = 'CS_AI_DISABLE';
export const SC_AI_DISABLED = 'SC_AI_DISABLED';
export const CS_AI_STATS = 'CS_AI_STATS';
export const SC_AI_STATS = 'SC_AI_STATS';
export const SC_AI_ACTION = 'SC_AI_ACTION';
export const CS_GET_SUGGESTION = 'CS_GET_SUGGESTION';
export const SC_SUGGESTION = 'SC_SUGGESTION';
