exports.CS_FOLD = 'CS_FOLD';
exports.CS_CHECK = 'CS_CHECK';
exports.CS_CALL = 'CS_CALL';
exports.CS_RAISE = 'CS_RAISE';
exports.WINNER = 'WINNER';
exports.CS_FETCH_LOBBY_INFO = 'CS_FETCH_LOBBY_INFO';
exports.SC_RECEIVE_LOBBY_INFO = 'SC_RECEIVE_LOBBY_INFO';
exports.SC_PLAYERS_UPDATED = 'SC_PLAYERS_UPDATED';
exports.CS_JOIN_TABLE = 'CS_JOIN_TABLE';
exports.SC_TABLE_JOINED = 'SC_TABLE_JOINED';
exports.CS_LEAVE_TABLE = 'CS_LEAVE_TABLE';
exports.SC_TABLE_LEFT = 'SC_TABLE_LEFT';
exports.SC_TABLES_UPDATED = 'SC_TABLES_UPDATED';
exports.SC_TABLE_UPDATED = 'SC_TABLE_UPDATED';
exports.TABLE_MESSAGE = 'TABLE_MESSAGE';         // no emit event
exports.CS_REBUY = 'CS_REBUY';
exports.CS_SIT_DOWN = 'CS_SIT_DOWN';
exports.CS_STAND_UP = 'CS_STAND_UP';
exports.SITTING_OUT = 'SITTING_OUT';         // no emit event
exports.SITTING_IN = 'SITTING_IN';         // no emit event
exports.CS_DISCONNECT = 'CS_DISCONNECT';
exports.CS_LOBBY_CONNECT = "CS_LOBBY_CONNECT";
exports.CS_LOBBY_DISCONNECT = "CS_LOBBY_DISCONNECT";
exports.SC_LOBBY_CONNECTED = "SC_LOBBY_CONNECTED";
exports.SC_LOBBY_DISCONNECTED = "SC_LOBBY_DISCONNECTED";
exports.CS_LOBBY_CHAT = "CS_LOBBY_CHAT";
exports.SC_LOBBY_CHAT = "SC_LOBBY_CHAT";

// Blockchain integration events
exports.CS_JOIN_TABLE_BLOCKCHAIN = 'CS_JOIN_TABLE_BLOCKCHAIN';
exports.CS_LEAVE_TABLE_BLOCKCHAIN = 'CS_LEAVE_TABLE_BLOCKCHAIN';
exports.SC_BLOCKCHAIN_STATUS = 'SC_BLOCKCHAIN_STATUS';
exports.SC_BLOCKCHAIN_TX_STATUS = 'SC_BLOCKCHAIN_TX_STATUS';
exports.SC_BLOCKCHAIN_ERROR = 'SC_BLOCKCHAIN_ERROR';
exports.SC_BLOCKCHAIN_SETTLEMENT = 'SC_BLOCKCHAIN_SETTLEMENT';
exports.SC_BALANCE_SYNCED = 'SC_BALANCE_SYNCED';

// Player-signed contract calls (frontend calls contract directly)
exports.CS_CONTRACT_JOIN_SUCCESS = 'CS_CONTRACT_JOIN_SUCCESS';
exports.CS_CONTRACT_JOIN_FAILED = 'CS_CONTRACT_JOIN_FAILED';
exports.CS_CONTRACT_LEAVE_SUCCESS = 'CS_CONTRACT_LEAVE_SUCCESS';
exports.CS_CONTRACT_LEAVE_FAILED = 'CS_CONTRACT_LEAVE_FAILED';

// Delegate (Server Proxy) events
exports.CS_SET_DELEGATE = 'CS_SET_DELEGATE';
exports.SC_DELEGATE_SET = 'SC_DELEGATE_SET';
exports.SC_DELEGATE_ERROR = 'SC_DELEGATE_ERROR';
exports.CS_CHECK_DELEGATE = 'CS_CHECK_DELEGATE';
exports.SC_DELEGATE_STATUS = 'SC_DELEGATE_STATUS';
exports.CS_REVOKE_DELEGATE = 'CS_REVOKE_DELEGATE';
exports.SC_DELEGATE_REVOKED = 'SC_DELEGATE_REVOKED';

// Tournament System events
exports.CS_TOURNAMENT_LIST = 'CS_TOURNAMENT_LIST';
exports.SC_TOURNAMENT_LIST = 'SC_TOURNAMENT_LIST';
exports.CS_TOURNAMENT_JOIN = 'CS_TOURNAMENT_JOIN';
exports.SC_TOURNAMENT_JOINED = 'SC_TOURNAMENT_JOINED';
exports.SC_TOURNAMENT_JOIN_ERROR = 'SC_TOURNAMENT_JOIN_ERROR';
exports.CS_TOURNAMENT_CANCEL = 'CS_TOURNAMENT_CANCEL';
exports.SC_TOURNAMENT_CANCELLED = 'SC_TOURNAMENT_CANCELLED';
exports.SC_TOURNAMENT_STARTED = 'SC_TOURNAMENT_STARTED';
exports.SC_TOURNAMENT_ENDED = 'SC_TOURNAMENT_ENDED';
exports.SC_TOURNAMENT_UPDATE = 'SC_TOURNAMENT_UPDATE';
exports.SC_TOURNAMENT_ELIMINATION = 'SC_TOURNAMENT_ELIMINATION';
exports.SC_TOURNAMENT_PRIZE = 'SC_TOURNAMENT_PRIZE';
// Tournament game actions (Task 12.6)
exports.CS_TOURNAMENT_FOLD = 'CS_TOURNAMENT_FOLD';
exports.CS_TOURNAMENT_CHECK = 'CS_TOURNAMENT_CHECK';
exports.CS_TOURNAMENT_CALL = 'CS_TOURNAMENT_CALL';
exports.CS_TOURNAMENT_RAISE = 'CS_TOURNAMENT_RAISE';
exports.CS_TOURNAMENT_RECONNECT = 'CS_TOURNAMENT_RECONNECT';
exports.SC_TOURNAMENT_GAME_STATE = 'SC_TOURNAMENT_GAME_STATE';
exports.SC_TOURNAMENT_ACTION_ERROR = 'SC_TOURNAMENT_ACTION_ERROR';

// NFT Achievement events
exports.CS_NFT_CHECK_ACHIEVEMENT = 'CS_NFT_CHECK_ACHIEVEMENT';
exports.SC_NFT_ACHIEVEMENT_EARNED = 'SC_NFT_ACHIEVEMENT_EARNED';
exports.SC_NFT_ACHIEVEMENT_NONE = 'SC_NFT_ACHIEVEMENT_NONE';
exports.CS_NFT_PREPARE_MINT = 'CS_NFT_PREPARE_MINT';
exports.SC_NFT_MINT_READY = 'SC_NFT_MINT_READY';
exports.SC_NFT_MINT_ERROR = 'SC_NFT_MINT_ERROR';
exports.CS_NFT_COLLECTION = 'CS_NFT_COLLECTION';
exports.SC_NFT_COLLECTION = 'SC_NFT_COLLECTION';

// CHIP Token events
exports.CS_CHIP_BALANCE = 'CS_CHIP_BALANCE';
exports.SC_CHIP_BALANCE = 'SC_CHIP_BALANCE';
exports.CS_CHIP_REWARD = 'CS_CHIP_REWARD';
exports.SC_CHIP_REWARDED = 'SC_CHIP_REWARDED';
exports.SC_CHIP_VIP_DISCOUNT = 'SC_CHIP_VIP_DISCOUNT';

// Staking events
exports.CS_STAKE_INFO = 'CS_STAKE_INFO';
exports.SC_STAKE_INFO = 'SC_STAKE_INFO';
exports.CS_STAKE_CREATE = 'CS_STAKE_CREATE';
exports.SC_STAKE_CREATED = 'SC_STAKE_CREATED';
exports.SC_STAKE_ERROR = 'SC_STAKE_ERROR';
exports.CS_STAKE_UNSTAKE = 'CS_STAKE_UNSTAKE';
exports.SC_STAKE_UNSTAKED = 'SC_STAKE_UNSTAKED';
exports.CS_STAKE_CLAIM_REWARD = 'CS_STAKE_CLAIM_REWARD';
exports.SC_STAKE_REWARD_CLAIMED = 'SC_STAKE_REWARD_CLAIMED';

// DAO Governance events
exports.CS_DAO_PROPOSALS = 'CS_DAO_PROPOSALS';
exports.SC_DAO_PROPOSALS = 'SC_DAO_PROPOSALS';
exports.CS_DAO_CREATE_PROPOSAL = 'CS_DAO_CREATE_PROPOSAL';
exports.SC_DAO_PROPOSAL_CREATED = 'SC_DAO_PROPOSAL_CREATED';
exports.CS_DAO_VOTE = 'CS_DAO_VOTE';
exports.SC_DAO_VOTED = 'SC_DAO_VOTED';
exports.SC_DAO_PROPOSAL_EXECUTED = 'SC_DAO_PROPOSAL_EXECUTED';
exports.SC_DAO_PROPOSAL_STATE_CHANGED = 'SC_DAO_PROPOSAL_STATE_CHANGED';
exports.SC_DELEGATE_REVOKED = 'SC_DELEGATE_REVOKED';
